### ISSUE TITLE
ERROR - MQTT connection error: argument 3: <type 'exceptions.TypeError'>: wrong type 

### ISSUE THREAD

**Issue by pepijng** [SevenW/Plugwise-2-py#5] opened 2015-02-13 11:20 UTC
On my new mosquito / Plugwise-2.py installation the following error message appears when connecting to mosquito from PW2py.
ERROR - MQTT connection error: argument 3: <type 'exceptions.TypeError'>: wrong type 
When using mosquito_pub or other mqtt enabled applications mosquito works fine.

Please advice

**Comment by SevenW** [comment] 2015-02-16 22:16
I do not immediately what is the problem. Can you provide me with some more details?
I suspect e versioning problem between PW2py and mosquito server, or PW2py and the python mosquitto client
What is the version of mosquitto you are using?
Which python client lib are you using? Did you specfically install the python MQTT client or are you using the code in this repository?  (in config/libraries). 

Where did this error occur? Can you add some more logging?

**Comment by SevenW** [comment] 2015-04-19 09:16
Error was caused by an updated api of on_connected from the "official" mosquitto python client. My code could optionally load the official client, and otherwise use a fallback to an embedded client which had differences in the api.
Solved by moving to the paho version of the python mqtt client and removing the embedded client. Also moved to the cleaner pip install for the external packages.

I was not able to reproduce exactly the same error message, but had something that looked related. For sure moving over to the new paho client code will require some time before it is free of bugs.

**Closed by SevenW** 2015-04-19 09:16 UTC
